<!-- @import "[TOC]" {cmd="toc" depthFrom=1 depthTo=6 orderedList=false} -->

<!-- code_chunk_output -->

- [事务](#事务)
  - [非托管事务](#非托管事务)
  - [托管事务](#托管事务)
    - [抛出错误以回滚](#抛出错误以回滚)

<!-- /code_chunk_output -->

# 事务

默认情况下,Sequelize 不使用事务

- 两种使用事务的方式
  - 非托管事务: 提交和回滚事务应由用户手动完成(通过调用适当的 Sequelize 方法).
  - 托管事务: 如果引发任何错误,Sequelize 将自动回滚事务,否则将提交事务. 另外,如果启用了CLS(连续本地存储),则事务回调中的所有查询将自动接收事务对象.

## 非托管事务

- 非托管事务 方法要求你在必要时手动提交和回滚事务

```ts
// 首先, 我们从你的连接开始一个事务并将其保存到一个变量中
const t = await sequelize.transaction();

try {

  // 然后,我们进行一些调用以将此事务作为参数传递:
  const user = await User.create({
    firstName: 'Bart',
    lastName: 'Simpson'
  }, { transaction: t });

  await user.addSibling({
    firstName: 'Lisa',
    lastName: 'Simpson'
  }, { transaction: t });

  // 如果执行到此行,且没有引发任何错误.
  // 我们提交事务.
  await t.commit();

} catch (error) {
  // 如果执行到达此行,则抛出错误.
  // 我们回滚事务.
  await t.rollback();
}
```

## 托管事务

托管事务会自动处理提交或回滚事务. 通过将回调传递给 sequelize.transaction 来启动托管事务. 这个回调可以是 async(通常是)的.

在这种情况下,将发生以下情况：

```ts
try {
const result = await sequelize.transaction(async (t) => {
    const user = await User.create({
        firstName: 'Abraham',
        lastName: 'Lincoln'
    }, { transaction: t });

    await user.setShooter({
        firstName: 'John',
        lastName: 'Boothe'
    }, { transaction: t });

    return user;

    });
    // 如果执行到此行,则表示事务已成功提交,`result`是事务返回的结果
    // `result` 就是从事务回调中返回的结果(在这种情况下为 `user`)

} catch (error) {

  // 如果执行到此,则发生错误.
  // 该事务已由 Sequelize 自动回滚！

}
```

### 抛出错误以回滚

```ts
await sequelize.transaction(async t => {
  const user = await User.create({
    firstName: 'Abraham',
    lastName: 'Lincoln'
  }, { transaction: t });

  // 查询成功,但我们仍要回滚！
  // 我们手动引发错误,以便 Sequelize 自动处理所有内容.
  throw new Error();
});
```
