<!-- @import "[TOC]" {cmd="toc" depthFrom=1 depthTo=6 orderedList=false} -->

<!-- code_chunk_output -->

- [错误处理](#错误处理)

<!-- /code_chunk_output -->

# 错误处理

在 Swift 中，错误由符合 Error 协议的类型值表示。这个空协议表明一个类型可用于错误处理。

```swift
// 定义错误枚举
enum VendingMachineError: Error {
    case invalidSelection
    case insufficientFunds(coinsNeeded: Int)
    case outOfStock
}
```

```swift
// 声明 throws 关键字
func canThrowErrors() throws -> String {
    throw VendingMachineError.outOfStock
}

```swift
do {
    try <#expression#>
    <#statements#>
} catch <#pattern 1#> {
    <#statements#>
} catch <#pattern 2#> where <#condition#> {
    <#statements#>
} catch <#pattern 3#>, <#pattern 4#> where <#condition#> {
    <#statements#>
} catch {
    <#statements#>
}
```

```swift
var vendingMachine = VendingMachine()
vendingMachine.coinsDeposited = 8
do {
    try buyFavoriteSnack(person: "Alice", vendingMachine: vendingMachine)
    print("Success! Yum.")
} catch VendingMachineError.invalidSelection {
    print("Invalid Selection.")
} catch VendingMachineError.outOfStock {
    print("Out of Stock.")
} catch VendingMachineError.insufficientFunds(let coinsNeeded) {
    print("Insufficient funds. Please insert an additional \(coinsNeeded) coins.")
} catch {
}

// 捕获多个相关错误的另一种方法是将它们列在 catch 之后，并用逗号分隔
func eat(item: String) throws {
    do {
        try vendingMachine.vend(itemNamed: item)
    } catch VendingMachineError.invalidSelection, VendingMachineError.insufficientFunds, VendingMachineError.outOfStock {
        print("Invalid selection, out of stock, or not enough money.")
    }
}
```

## 将错误转换为可选值

```swift
func someThrowingFunction() throws -> Int {
    // ...
}

let x = try? someThrowingFunction()

// 下面等价上面
let y: Int?
do {
    y = try someThrowingFunction()
} catch {
    y = nil
}

```

## 禁用错误传播

```swift
let photo = try! loadImage(atPath: "./Resources/John Appleseed.jpg")
```

## 指定清理操作

- 使用 defer 语句在代码执行离开当前代码块之前执行一组语句。
- 该语句允许您执行任何必要的清理操作，无论执行如何离开当前代码块 - `是否由于抛出错误`或`由于 return` 或 `break 语句`来确保关闭文件描述符并释放手动分配的内存。

```swift
func processFile(filename: String) throws {
    if exists(filename) {
        let file = open(filename)
        defer {
            close(file)
        }
        while let line = try file.readline() {
            // Work with the file.
        }
        // close(file) is called here, at the end of the scope.
    }
}
```
